// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	entities "security_audit_tool/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// VersionControlSystemPort is an autogenerated mock type for the VersionControlSystemPort type
type VersionControlSystemPort struct {
	mock.Mock
}

// GetInfo provides a mock function with given fields:
func (_m *VersionControlSystemPort) GetInfo() (entities.VersionControlData, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 entities.VersionControlData
	var r1 error
	if rf, ok := ret.Get(0).(func() (entities.VersionControlData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() entities.VersionControlData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entities.VersionControlData)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVersionControlSystemPort creates a new instance of VersionControlSystemPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVersionControlSystemPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *VersionControlSystemPort {
	mock := &VersionControlSystemPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
